import { useAppState } from '../context/AppContext';
import { useState, useMemo } from 'react';
import { getDaysUntilExpiry, formatDate } from '../lib/dateUtils';
import { findDuplicateReferrals, getSLACategory, getSLALabel, calculateReadiness, getRecommendedNextAction, getStageAgingHours, getReferralToSOCDays, calculatePipelineAnalytics } from '../utils/dataLogic';
import type { Referral, ReferralDocument } from '../types';
import {
  ClipboardList, AlertTriangle, Clock, FileText, Upload, X,
  Eye, Brain, User, Calendar, CheckCircle, XCircle, Copy,
  ArrowRight, Activity, Timer, BarChart3, TrendingUp
} from 'lucide-react';

const stages: Referral['stage'][] = ['New', 'Missing Docs', 'Eligibility', 'Staffing', 'Scheduled', 'Started', 'Declined'];
const stageColors: Record<string, string> = {
  'New': 'bg-sky-100 text-sky-800 border-sky-200',
  'Missing Docs': 'bg-amber-100 text-amber-800 border-amber-200',
  'Eligibility': 'bg-violet-100 text-violet-800 border-violet-200',
  'Staffing': 'bg-orange-100 text-orange-800 border-orange-200',
  'Scheduled': 'bg-emerald-100 text-emerald-800 border-emerald-200',
  'Started': 'bg-green-100 text-green-800 border-green-200',
  'Declined': 'bg-red-100 text-red-800 border-red-200',
};

const readinessColors: Record<string, string> = {
  'Missing Docs': 'badge-urgent',
  'Ready for Eligibility': 'badge-warning',
  'Ready for Staffing': 'badge-info',
  'Ready for SOC': 'badge-success',
};

function SLAClock({ deadline, deadlineAt }: { deadline: string; deadlineAt?: string }) {
  const target = deadlineAt || deadline;
  const category = getSLACategory(target);
  const label = getSLALabel(target);
  const color = category === 'Breach' ? 'text-red-600' : category === 'Risk' ? 'text-amber-600' : 'text-emerald-500';
  return (
    <span className={`flex items-center gap-1 text-xs font-medium ${color}`} data-testid="sla-clock">
      <Clock size={11} />
      {label}
      {category === 'Breach' && <span className="badge badge-urgent text-[8px] ml-1">BREACH</span>}
      {category === 'Risk' && <span className="badge badge-warning text-[8px] ml-1">RISK</span>}
    </span>
  );
}

function DocChecklist({ documents, onUpload }: { documents: ReferralDocument[]; onUpload: (docType: string) => void }) {
  return (
    <div className="space-y-1.5">
      {documents.map((doc) => (
        <div key={doc.type} className={`flex items-center justify-between px-3 py-2 rounded-lg text-xs border ${doc.uploaded ? 'bg-emerald-50 border-emerald-200' : 'bg-red-50 border-red-200'}`}>
          <div className="flex items-center gap-2">
            {doc.uploaded ? <CheckCircle size={13} className="text-emerald-600" /> : <XCircle size={13} className="text-red-500" />}
            <span className={doc.uploaded ? 'text-emerald-700' : 'text-red-700 font-medium'}>{doc.type}</span>
          </div>
          {doc.uploaded ? (
            <span className="text-[10px] text-emerald-500">{doc.uploadedAt ? formatDate(doc.uploadedAt) : 'Uploaded'}</span>
          ) : (
            <button onClick={() => onUpload(doc.type)} className="flex items-center gap-1 text-[10px] text-sky-600 hover:text-sky-800">
              <Upload size={10} /> Upload
            </button>
          )}
        </div>
      ))}
    </div>
  );
}

function AISummary({ referral }: { referral: Referral }) {
  const missingDocs = referral.documents.filter(d => !d.uploaded).length;
  const socDays = getDaysUntilExpiry(referral.dischargeDate);

  return (
    <div className="p-3 bg-violet-50 border border-violet-200 rounded-lg">
      <p className="text-xs font-semibold text-violet-800 flex items-center gap-1.5 mb-2">
        <Brain size={12} /> Rules-Based Demo Summary
      </p>
      <p className="text-xs text-violet-700 leading-relaxed">
        {referral.patientInitials} referred from {referral.source} for {referral.serviceType} ({referral.urgency}).
        {missingDocs > 0 ? ` ${missingDocs} document${missingDocs > 1 ? 's' : ''} still missing.` : ' All documents received.'}
        {referral.insuranceStatus === 'Verified' ? ' Insurance verified.' : ` Insurance ${referral.insuranceStatus.toLowerCase()}.`}
        {socDays !== null && ` SOC ${socDays < 0 ? 'overdue' : `in ${socDays} days`}.`}
        {referral.assignedOwner && ` Owned by ${referral.assignedOwner}.`}
      </p>
      <p className="text-[10px] text-violet-500 mt-1.5 italic">
        ⚠ This summary is generated by deterministic rules, not AI/ML. For demo purposes only.
      </p>
    </div>
  );
}

function DetailDrawer({ referralId, onClose, onUpload, onMoveStage }: {
  referralId: string;
  onClose: () => void;
  onUpload: (id: string, docType: string) => void;
  onMoveStage: (id: string, stage: Referral['stage']) => void;
}) {
  const { state } = useAppState();
  // Derive referral from state so it's always fresh
  const referral = state.referrals.find(r => r.id === referralId);
  if (!referral) return null;

  const duplicates = findDuplicateReferrals(referral, state.referrals);
  const readiness = calculateReadiness(referral);
  const nextAction = getRecommendedNextAction(referral);
  const agingHours = getStageAgingHours(referral.createdAt);
  const socDays = getReferralToSOCDays(referral);
  const allDocsUploaded = referral.documents.every(d => d.uploaded);

  return (
    <div className="fixed inset-0 z-40 flex">
      <div className="flex-1 bg-black/30" onClick={onClose} />
      <div className="w-[500px] bg-white shadow-2xl overflow-y-auto border-l border-advisa-border">
        <div className="sticky top-0 bg-white border-b border-advisa-border px-5 py-4 flex items-center justify-between z-10">
          <div>
            <p className="text-lg font-bold text-slate-800">{referral.patientInitials}</p>
            <p className="text-xs text-slate-400">{referral.source} · {referral.serviceType}</p>
          </div>
          <button onClick={onClose} className="p-1.5 hover:bg-slate-100 rounded-lg transition-colors"><X size={18} /></button>
        </div>

        <div className="p-5 space-y-5">
          {/* Duplicate Warning */}
          {duplicates.length > 0 && (
            <div className="p-3 bg-amber-50 border border-amber-200 rounded-lg flex items-center gap-2 text-xs text-amber-800" data-testid="duplicate-warning">
              <Copy size={13} />
              <span><strong>Possible duplicate:</strong> {duplicates.length} similar referral{duplicates.length > 1 ? 's' : ''} found ({duplicates.map(d => d.id).join(', ')})</span>
            </div>
          )}

          {/* Readiness + Next Action */}
          <div className="p-3 bg-sky-50 border border-sky-200 rounded-lg">
            <div className="flex items-center justify-between mb-2">
              <p className="text-xs font-semibold text-sky-800 flex items-center gap-1"><Activity size={12} /> Readiness</p>
              <span className={`badge ${readinessColors[readiness]}`}>{readiness}</span>
            </div>
            <p className="text-xs text-sky-700 flex items-center gap-1">
              <ArrowRight size={10} /> <strong>Next:</strong> {nextAction}
            </p>
            {allDocsUploaded && referral.stage !== 'Started' && referral.stage !== 'Declined' && readiness === 'Ready for Eligibility' && (
              <button onClick={() => onMoveStage(referral.id, 'Eligibility')} className="btn-primary text-xs mt-2" data-testid="move-to-eligibility">
                <ArrowRight size={11} /> Move to Eligibility Review
              </button>
            )}
            {readiness === 'Ready for Staffing' && referral.stage !== 'Scheduled' && referral.stage !== 'Started' && (
              <button onClick={() => onMoveStage(referral.id, 'Staffing')} className="btn-primary text-xs mt-2">
                <ArrowRight size={11} /> Move to Staffing
              </button>
            )}
          </div>

          {/* Status / SLA */}
          <div className="grid grid-cols-2 gap-3">
            <div className="p-3 bg-slate-50 rounded-lg">
              <p className="stat-label">Stage</p>
              <span className={`badge ${stageColors[referral.stage] || 'badge-neutral'} mt-1`}>{referral.stage}</span>
            </div>
            <div className="p-3 bg-slate-50 rounded-lg">
              <p className="stat-label">SLA Deadline</p>
              <SLAClock deadline={referral.slaDeadline} deadlineAt={referral.slaDeadlineAt} />
            </div>
            <div className="p-3 bg-slate-50 rounded-lg">
              <p className="stat-label">Urgency</p>
              <span className={`badge mt-1 ${referral.urgency === 'Immediate' ? 'badge-urgent' : referral.urgency.includes('Urgent') ? 'badge-warning' : 'badge-neutral'}`}>
                {referral.urgency}
              </span>
            </div>
            <div className="p-3 bg-slate-50 rounded-lg">
              <p className="stat-label">Insurance</p>
              <span className={`badge mt-1 ${referral.insuranceStatus === 'Verified' ? 'badge-success' : referral.insuranceStatus === 'Denied' ? 'badge-urgent' : 'badge-warning'}`}>
                {referral.insuranceStatus}
              </span>
            </div>
          </div>

          {/* Stage Aging + SOC Timer */}
          <div className="grid grid-cols-2 gap-3">
            <div className="p-3 bg-slate-50 rounded-lg flex items-center gap-2">
              <Timer size={13} className="text-slate-400" />
              <div>
                <p className="stat-label">Stage Aging</p>
                <p className="text-sm font-semibold text-slate-700">{agingHours}h in pipeline</p>
              </div>
            </div>
            <div className="p-3 bg-slate-50 rounded-lg flex items-center gap-2">
              <BarChart3 size={13} className="text-slate-400" />
              <div>
                <p className="stat-label">Referral→SOC</p>
                <p className="text-sm font-semibold text-slate-700">{socDays !== null ? `${socDays} days` : 'In progress'}</p>
              </div>
            </div>
          </div>

          {/* Owner & Follow-Up */}
          <div className="grid grid-cols-2 gap-3">
            <div className="flex items-center gap-2 text-sm">
              <User size={13} className="text-slate-400" />
              <span className="text-slate-600">Owner: <strong>{referral.assignedOwner}</strong></span>
            </div>
            <div className="flex items-center gap-2 text-sm">
              <Calendar size={13} className="text-slate-400" />
              <span className="text-slate-600">Follow-up: <strong>{formatDate(referral.nextFollowUpDate)}</strong></span>
            </div>
          </div>

          {/* Decline Reason */}
          {referral.stage === 'Declined' && referral.declineReason && (
            <div className="p-3 bg-red-50 border border-red-200 rounded-lg text-xs text-red-700">
              <p className="font-semibold">Decline Reason</p>
              <p className="mt-1">{referral.declineReason}</p>
              {referral.lostReason && <p className="mt-1 text-red-500">Lost reason: {referral.lostReason}</p>}
            </div>
          )}

          {/* Document Checklist */}
          <div>
            <p className="section-title mb-2 flex items-center gap-2"><FileText size={13} /> Document Checklist</p>
            {referral.documents.filter(d => !d.uploaded).length > 0 && (
              <div className="mb-2 p-2 bg-red-50 border border-red-200 rounded-lg flex items-center gap-2 text-xs text-red-700">
                <AlertTriangle size={11} />
                {referral.documents.filter(d => !d.uploaded).length} missing document{referral.documents.filter(d => !d.uploaded).length > 1 ? 's' : ''}
              </div>
            )}
            <DocChecklist documents={referral.documents} onUpload={(docType) => onUpload(referral.id, docType)} />
          </div>

          {/* SOC Deadline */}
          <div className="p-3 bg-slate-50 rounded-lg">
            <p className="stat-label">SOC Deadline</p>
            <div className="flex items-center gap-2 mt-1">
              <Clock size={13} className="text-slate-500" />
              <span className="text-sm font-medium">{formatDate(referral.dischargeDate)}</span>
              <SLAClock deadline={referral.dischargeDate} />
            </div>
          </div>

          {/* Timeline */}
          {referral.timeline.length > 0 && (
            <div>
              <p className="section-title mb-2 flex items-center gap-2"><Activity size={13} /> Timeline</p>
              <div className="space-y-2 relative pl-4 border-l-2 border-advisa-border">
                {referral.timeline.map((event, idx) => (
                  <div key={idx} className="relative">
                    <div className="absolute -left-[21px] top-1 w-3 h-3 bg-advisa-accent rounded-full border-2 border-white" />
                    <div className="text-xs">
                      <p className="font-semibold text-slate-700">{event.action}</p>
                      <p className="text-slate-400">{event.date} · {event.user}</p>
                      {event.details && <p className="text-slate-500 mt-0.5">{event.details}</p>}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* AI Summary */}
          <AISummary referral={referral} />
        </div>
      </div>
    </div>
  );
}

export default function Referrals() {
  const { state, updateReferralStage, updateReferral, addAuditEntry, addToast } = useAppState();
  const [viewMode, setViewMode] = useState<'table' | 'kanban'>('table');
  const [filterStage, setFilterStage] = useState('All');
  const [filterUrgency, setFilterUrgency] = useState('All');
  const [selectedReferralId, setSelectedReferralId] = useState<string | null>(null);
  const [showAnalytics, setShowAnalytics] = useState(false);

  const urgencies = ['All', 'Routine', 'Urgent 24-48 hours', 'Immediate'];

  const filtered = state.referrals.filter(r =>
    (filterStage === 'All' || r.stage === filterStage) &&
    (filterUrgency === 'All' || r.urgency === filterUrgency)
  );

  const analytics = useMemo(() => calculatePipelineAnalytics(state.referrals), [state.referrals]);

  // Lost referral reason analytics
  const declinedReferrals = state.referrals.filter(r => r.stage === 'Declined' && r.lostReason);
  const lostReasonCounts = declinedReferrals.reduce<Record<string, number>>((acc, r) => {
    if (r.lostReason) acc[r.lostReason] = (acc[r.lostReason] || 0) + 1;
    return acc;
  }, {});

  const handleStageChange = (id: string, newStage: Referral['stage']) => {
    const ref = state.referrals.find(r => r.id === id);
    if (!ref) return;
    const oldStage = ref.stage;
    const now = new Date().toISOString();
    const nowDate = now.split('T')[0];
    updateReferralStage(id, newStage);
    // Set stage timestamps
    const tsUpdates: Record<string, string> = {};
    if (newStage === 'Missing Docs' && !ref.stageTimestamps.docsRequestedAt) tsUpdates.docsRequestedAt = now;
    if (newStage === 'Eligibility' && !ref.stageTimestamps.eligibilityStartedAt) tsUpdates.eligibilityStartedAt = now;
    if (newStage === 'Staffing' && !ref.stageTimestamps.staffingStartedAt) tsUpdates.staffingStartedAt = now;
    if (newStage === 'Scheduled' && !ref.stageTimestamps.socScheduledAt) tsUpdates.socScheduledAt = now;
    if (newStage === 'Started' && !ref.stageTimestamps.socCompletedAt) tsUpdates.socCompletedAt = now;
    if (newStage === 'Declined' && !ref.stageTimestamps.declinedAt) tsUpdates.declinedAt = now;

    updateReferral(id, {
      timeline: [...ref.timeline, { date: nowDate, action: `Stage → ${newStage}`, user: state.currentUser.name }],
      readiness: calculateReadiness({ ...ref, stage: newStage }),
      recommendedNextAction: getRecommendedNextAction({ ...ref, stage: newStage }),
      stageTimestamps: { ...ref.stageTimestamps, ...tsUpdates },
    });
    addAuditEntry({
      user: state.currentUser.name, role: state.currentUser.role,
      action: 'Updated', recordType: 'Referral', recordId: id,
      details: `Stage changed to ${newStage} for ${ref.patientInitials}`,
      before: oldStage, after: newStage,
    });
    addToast(`${ref.patientInitials} moved to ${newStage}`, 'success');
  };

  const handleDocUpload = (referralId: string, docType: string) => {
    const ref = state.referrals.find(r => r.id === referralId);
    if (!ref) return;
    const now = new Date().toISOString();
    const nowDate = now.split('T')[0];
    const updatedDocs = ref.documents.map(d =>
      d.type === docType ? { ...d, uploaded: true, uploadedAt: now } : d
    );
    const docsUploaded = updatedDocs.filter(d => d.uploaded).length;
    const missing = updatedDocs.filter(d => !d.uploaded).length;
    const physOrders = updatedDocs.find(d => d.type === 'Physician Orders')?.uploaded ?? ref.physicianOrdersReceived;
    const allDone = updatedDocs.every(d => d.uploaded);
    const newReadiness = calculateReadiness({ ...ref, documents: updatedDocs });
    const newNextAction = getRecommendedNextAction({ ...ref, documents: updatedDocs });

    const tsUpdates: Record<string, string> = {};
    if (allDone && !ref.stageTimestamps.docsCompleteAt) tsUpdates.docsCompleteAt = now;

    updateReferral(referralId, {
      documents: updatedDocs,
      documentsUploaded: docsUploaded,
      missingItems: missing,
      physicianOrdersReceived: physOrders,
      readiness: newReadiness,
      recommendedNextAction: newNextAction,
      timeline: [...ref.timeline, { date: nowDate, action: `Uploaded: ${docType}`, user: state.currentUser.name }],
      stageTimestamps: { ...ref.stageTimestamps, ...tsUpdates },
    });
    addAuditEntry({
      user: state.currentUser.name, role: state.currentUser.role,
      action: 'Updated', recordType: 'Referral', recordId: referralId,
      details: `Uploaded ${docType} for ${ref.patientInitials}`,
    });
    addToast(`${docType} uploaded for ${ref.patientInitials}`, 'success');

    if (allDone && (ref.stage === 'Missing Docs' || ref.stage === 'New')) {
      addToast(`All documents received for ${ref.patientInitials} — Ready for Eligibility Review`, 'info');
    }
  };

  const missingDocsCount = state.referrals.reduce((sum, r) => sum + r.documents.filter(d => !d.uploaded).length, 0);

  return (
    <div>
      <div className="flex justify-between items-start mb-6">
        <div>
          <h2 className="page-title flex items-center gap-2">
            <ClipboardList size={22} className="text-advisa-accent" />
            Referral Pipeline
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            {state.referrals.length} referrals · {missingDocsCount} missing docs
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={() => setShowAnalytics(!showAnalytics)} className={`btn-${showAnalytics ? 'primary' : 'secondary'} text-xs py-1.5`}>
            <TrendingUp size={13} /> Analytics
          </button>
          <button onClick={() => setViewMode('table')} className={`btn-${viewMode === 'table' ? 'primary' : 'secondary'} text-xs py-1.5`}>Table</button>
          <button onClick={() => setViewMode('kanban')} className={`btn-${viewMode === 'kanban' ? 'primary' : 'secondary'} text-xs py-1.5`}>Kanban</button>
        </div>
      </div>

      {/* Referral-to-SOC Analytics Panel */}
      {showAnalytics && (
        <div className="card mb-5 bg-gradient-to-r from-sky-50 to-violet-50 border-advisa-accent/20" data-testid="pipeline-analytics">
          <p className="text-sm font-bold text-slate-800 flex items-center gap-2 mb-3"><BarChart3 size={14} className="text-advisa-accent" /> Referral-to-SOC Analytics</p>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-4">
            <div className="p-3 bg-white/60 rounded-lg text-center">
              <p className="text-[10px] text-slate-500">Avg Referral→SOC</p>
              <p className="text-xl font-bold text-sky-600">{analytics.avgReferralToSOC ?? '—'}d</p>
            </div>
            <div className="p-3 bg-white/60 rounded-lg text-center">
              <p className="text-[10px] text-slate-500">Median Referral→SOC</p>
              <p className="text-xl font-bold text-violet-600">{analytics.medianReferralToSOC ?? '—'}d</p>
            </div>
            <div className="p-3 bg-white/60 rounded-lg text-center">
              <p className="text-[10px] text-slate-500">Stuck (&gt;48h)</p>
              <p className="text-xl font-bold text-amber-600">{Object.values(analytics.stuckByOwner).reduce((a, b) => a + b, 0)}</p>
            </div>
            <div className="p-3 bg-white/60 rounded-lg text-center">
              <p className="text-[10px] text-slate-500">Lost Referrals</p>
              <p className="text-xl font-bold text-red-600">{Object.values(analytics.lostReasonCounts).reduce((a, b) => a + b, 0)}</p>
            </div>
          </div>

          {/* Avg time per stage */}
          {Object.keys(analytics.avgTimePerStage).length > 0 && (
            <div className="mb-3">
              <p className="text-xs font-semibold text-slate-600 mb-1">Avg Hours per Stage</p>
              <div className="flex flex-wrap gap-2">
                {Object.entries(analytics.avgTimePerStage).map(([stage, hrs]) => (
                  <div key={stage} className="px-2 py-1 bg-white rounded border border-advisa-border text-xs">
                    <span className="text-slate-500">{stage}:</span> <strong>{hrs}h</strong>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Conversion by source */}
          {Object.keys(analytics.conversionBySource).length > 0 && (
            <div>
              <p className="text-xs font-semibold text-slate-600 mb-1">Conversion by Source</p>
              <div className="flex flex-wrap gap-2">
                {Object.entries(analytics.conversionBySource).map(([src, data]) => (
                  <div key={src} className="px-2 py-1 bg-white rounded border border-advisa-border text-xs">
                    <span className="text-slate-500">{src}:</span> <strong className={data.rate >= 70 ? 'text-emerald-600' : data.rate >= 50 ? 'text-amber-600' : 'text-red-600'}>{data.rate}%</strong>
                    <span className="text-slate-400 ml-1">({data.converted}/{data.total})</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      {/* Filters */}
      <div className="flex gap-3 mb-5 flex-wrap">
        <select className="select" value={filterStage} onChange={e => setFilterStage(e.target.value)}>
          <option value="All">All Stages</option>
          {stages.map(s => <option key={s} value={s}>{s}</option>)}
        </select>
        <select className="select" value={filterUrgency} onChange={e => setFilterUrgency(e.target.value)}>
          {urgencies.map(u => <option key={u} value={u}>{u === 'All' ? 'All Urgencies' : u}</option>)}
        </select>
      </div>

      {/* Lost Referral Reason Analytics */}
      {Object.keys(lostReasonCounts).length > 0 && (
        <div className="card mb-5 bg-red-50/50 border-red-200">
          <p className="section-title mb-2 flex items-center gap-2 text-red-800"><XCircle size={13} /> Lost Referral Reasons</p>
          <div className="flex gap-3 flex-wrap">
            {Object.entries(lostReasonCounts).map(([reason, count]) => (
              <div key={reason} className="px-3 py-1.5 bg-white rounded-lg border border-red-200 text-xs">
                <span className="text-red-700 font-medium">{reason}</span>
                <span className="ml-2 badge badge-urgent text-[10px]">{count}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {viewMode === 'kanban' ? (
        <div className="flex gap-3 overflow-x-auto pb-4">
          {stages.filter(s => s !== 'Declined').map(stage => {
            const stageReferrals = filtered.filter(r => r.stage === stage);
            return (
              <div key={stage} className="min-w-[220px] flex-shrink-0">
                <div className={`px-3 py-2 rounded-t-lg text-xs font-semibold border ${stageColors[stage]}`}>
                  {stage} ({stageReferrals.length})
                </div>
                <div className="bg-slate-50 border border-t-0 border-advisa-border rounded-b-lg p-2 space-y-2 min-h-[200px]">
                  {stageReferrals.map(r => (
                    <div key={r.id} onClick={() => setSelectedReferralId(r.id)}
                      className="bg-white p-3 rounded-lg border border-advisa-border shadow-sm hover:shadow-card cursor-pointer transition-all">
                      <div className="flex items-center justify-between mb-1">
                        <span className="font-semibold text-sm text-slate-800">{r.patientInitials}</span>
                        <span className={`badge text-[10px] ${r.urgency === 'Immediate' ? 'badge-urgent' : r.urgency.includes('Urgent') ? 'badge-warning' : 'badge-neutral'}`}>
                          {r.urgency === 'Immediate' ? '🔴' : r.urgency.includes('Urgent') ? '🟡' : '⚪'} {r.urgency.split(' ')[0]}
                        </span>
                      </div>
                      <p className="text-[10px] text-slate-500">{r.source}</p>
                      <p className="text-[10px] text-slate-400">{r.serviceType}</p>
                      <div className="flex items-center justify-between mt-2">
                        <SLAClock deadline={r.slaDeadline} deadlineAt={r.slaDeadlineAt} />
                        {r.documents.some(d => !d.uploaded) && (
                          <span className="text-[10px] text-red-500 flex items-center gap-0.5"><AlertTriangle size={9} /> Docs</span>
                        )}
                      </div>
                      <div className="mt-1">
                        <span className={`badge text-[8px] ${readinessColors[r.readiness]}`}>{r.readiness}</span>
                      </div>
                    </div>
                  ))}
                  {stageReferrals.length === 0 && <p className="text-[10px] text-slate-300 text-center py-4">Empty</p>}
                </div>
              </div>
            );
          })}
        </div>
      ) : (
        <div className="card p-0 overflow-hidden">
          <table className="w-full text-sm">
            <thead>
              <tr>
                <th className="table-head">Patient</th>
                <th className="table-head">Service</th>
                <th className="table-head">Urgency</th>
                <th className="table-head">Source</th>
                <th className="table-head">Docs</th>
                <th className="table-head">SLA</th>
                <th className="table-head">Readiness</th>
                <th className="table-head">Owner</th>
                <th className="table-head">Stage</th>
                <th className="table-head">Actions</th>
              </tr>
            </thead>
            <tbody>
              {filtered.map(r => {
                const missingDocs = r.documents.filter(d => !d.uploaded).length;
                return (
                  <tr key={r.id} className="hover:bg-slate-50 transition-colors">
                    <td className="table-cell font-semibold text-slate-800">{r.patientInitials}</td>
                    <td className="table-cell"><span className="badge badge-info">{r.serviceType}</span></td>
                    <td className="table-cell">
                      <span className={`badge ${r.urgency === 'Immediate' ? 'badge-urgent' : r.urgency.includes('Urgent') ? 'badge-warning' : 'badge-neutral'}`}>{r.urgency}</span>
                    </td>
                    <td className="table-cell text-slate-500">{r.source}</td>
                    <td className="table-cell">
                      {missingDocs > 0 ? (
                        <span className="text-red-600 text-xs font-medium flex items-center gap-1"><AlertTriangle size={11} /> {missingDocs} missing</span>
                      ) : (
                        <span className="text-emerald-600 text-xs flex items-center gap-1"><CheckCircle size={11} /> Complete</span>
                      )}
                    </td>
                    <td className="table-cell"><SLAClock deadline={r.slaDeadline} deadlineAt={r.slaDeadlineAt} /></td>
                    <td className="table-cell"><span className={`badge text-[10px] ${readinessColors[r.readiness]}`}>{r.readiness}</span></td>
                    <td className="table-cell text-slate-500 text-xs">{r.assignedOwner}</td>
                    <td className="table-cell">
                      <select value={r.stage} onChange={e => handleStageChange(r.id, e.target.value as Referral['stage'])} className="text-xs px-2 py-1 border border-advisa-border rounded-md bg-white">
                        {stages.map(s => <option key={s} value={s}>{s}</option>)}
                      </select>
                    </td>
                    <td className="table-cell">
                      <button onClick={() => setSelectedReferralId(r.id)} className="text-advisa-accent hover:text-advisa-accent-dark transition-colors">
                        <Eye size={15} />
                      </button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
          {filtered.length === 0 && <div className="text-center py-12 text-slate-400 text-sm">No referrals match your filters</div>}
        </div>
      )}

      {/* Detail Drawer — uses ID, derives fresh referral from state */}
      {selectedReferralId && (
        <DetailDrawer
          referralId={selectedReferralId}
          onClose={() => setSelectedReferralId(null)}
          onUpload={handleDocUpload}
          onMoveStage={handleStageChange}
        />
      )}
    </div>
  );
}
