import { useAppState } from '../context/AppContext';
import { useState } from 'react';
import { getDaysUntilExpiry, formatDate } from '../lib/dateUtils';
import { findDuplicateReferrals } from '../utils/dataLogic';
import type { Referral, ReferralDocument } from '../types';
import {
  ClipboardList, AlertTriangle, Clock, FileText, Upload, X,
  Eye, Brain, User, Calendar, CheckCircle, XCircle, Copy
} from 'lucide-react';

const stages: Referral['stage'][] = ['New', 'Missing Docs', 'Eligibility', 'Staffing', 'Scheduled', 'Started', 'Declined'];
const stageColors: Record<string, string> = {
  'New': 'bg-sky-100 text-sky-800 border-sky-200',
  'Missing Docs': 'bg-amber-100 text-amber-800 border-amber-200',
  'Eligibility': 'bg-violet-100 text-violet-800 border-violet-200',
  'Staffing': 'bg-orange-100 text-orange-800 border-orange-200',
  'Scheduled': 'bg-emerald-100 text-emerald-800 border-emerald-200',
  'Started': 'bg-green-100 text-green-800 border-green-200',
  'Declined': 'bg-red-100 text-red-800 border-red-200',
};

function SLAClock({ deadline }: { deadline: string }) {
  const daysLeft = getDaysUntilExpiry(deadline);
  const color = daysLeft < 0 ? 'text-red-600' : daysLeft <= 1 ? 'text-red-500' : daysLeft <= 3 ? 'text-amber-500' : 'text-emerald-500';
  return (
    <span className={`flex items-center gap-1 text-xs font-medium ${color}`}>
      <Clock size={11} />
      {daysLeft < 0 ? `${Math.abs(daysLeft)}d overdue` : `${daysLeft}d left`}
    </span>
  );
}

function DocChecklist({ documents, onUpload }: { documents: ReferralDocument[]; onUpload: (docType: string) => void }) {
  return (
    <div className="space-y-1.5">
      {documents.map((doc) => (
        <div key={doc.type} className={`flex items-center justify-between px-3 py-2 rounded-lg text-xs border ${doc.uploaded ? 'bg-emerald-50 border-emerald-200' : 'bg-red-50 border-red-200'}`}>
          <div className="flex items-center gap-2">
            {doc.uploaded ? <CheckCircle size={13} className="text-emerald-600" /> : <XCircle size={13} className="text-red-500" />}
            <span className={doc.uploaded ? 'text-emerald-700' : 'text-red-700 font-medium'}>{doc.type}</span>
          </div>
          {doc.uploaded ? (
            <span className="text-[10px] text-emerald-500">{doc.uploadedAt ? formatDate(doc.uploadedAt) : 'Uploaded'}</span>
          ) : (
            <button onClick={() => onUpload(doc.type)} className="flex items-center gap-1 text-[10px] text-sky-600 hover:text-sky-800">
              <Upload size={10} /> Upload
            </button>
          )}
        </div>
      ))}
    </div>
  );
}

function AISummary({ referral }: { referral: Referral }) {
  const missingDocs = referral.documents.filter(d => !d.uploaded).length;
  const socDays = getDaysUntilExpiry(referral.dischargeDate);

  return (
    <div className="p-3 bg-violet-50 border border-violet-200 rounded-lg">
      <p className="text-xs font-semibold text-violet-800 flex items-center gap-1.5 mb-2">
        <Brain size={12} /> Rules-Based Demo Summary
      </p>
      <p className="text-xs text-violet-700 leading-relaxed">
        {referral.patientInitials} referred from {referral.source} for {referral.serviceType} ({referral.urgency}).
        {missingDocs > 0 ? ` ${missingDocs} document${missingDocs > 1 ? 's' : ''} still missing.` : ' All documents received.'}
        {referral.insuranceStatus === 'Verified' ? ' Insurance verified.' : ` Insurance ${referral.insuranceStatus.toLowerCase()}.`}
        {socDays !== null && ` SOC ${socDays < 0 ? 'overdue' : `in ${socDays} days`}.`}
        {referral.assignedOwner && ` Owned by ${referral.assignedOwner}.`}
      </p>
      <p className="text-[10px] text-violet-500 mt-1.5 italic">
        ⚠ This summary is generated by deterministic rules, not AI/ML. For demo purposes only.
      </p>
    </div>
  );
}

function DetailDrawer({ referral, onClose, onUpload }: { referral: Referral; onClose: () => void; onUpload: (id: string, docType: string) => void }) {
  const { state } = useAppState();
  const duplicates = findDuplicateReferrals(referral, state.referrals);

  return (
    <div className="fixed inset-0 z-40 flex">
      <div className="flex-1 bg-black/30" onClick={onClose} />
      <div className="w-[480px] bg-white shadow-2xl overflow-y-auto border-l border-advisa-border">
        <div className="sticky top-0 bg-white border-b border-advisa-border px-5 py-4 flex items-center justify-between z-10">
          <div>
            <p className="text-lg font-bold text-slate-800">{referral.patientInitials}</p>
            <p className="text-xs text-slate-400">{referral.source} · {referral.serviceType}</p>
          </div>
          <button onClick={onClose} className="p-1.5 hover:bg-slate-100 rounded-lg transition-colors"><X size={18} /></button>
        </div>

        <div className="p-5 space-y-5">
          {/* Duplicate Warning */}
          {duplicates.length > 0 && (
            <div className="p-3 bg-amber-50 border border-amber-200 rounded-lg flex items-center gap-2 text-xs text-amber-800">
              <Copy size={13} />
              <span><strong>Possible duplicate:</strong> {duplicates.length} similar referral{duplicates.length > 1 ? 's' : ''} found ({duplicates.map(d => d.id).join(', ')})</span>
            </div>
          )}

          {/* Status / SLA */}
          <div className="grid grid-cols-2 gap-3">
            <div className="p-3 bg-slate-50 rounded-lg">
              <p className="stat-label">Stage</p>
              <span className={`badge ${stageColors[referral.stage] || 'badge-neutral'} mt-1`}>{referral.stage}</span>
            </div>
            <div className="p-3 bg-slate-50 rounded-lg">
              <p className="stat-label">SLA Deadline</p>
              <SLAClock deadline={referral.slaDeadline} />
            </div>
            <div className="p-3 bg-slate-50 rounded-lg">
              <p className="stat-label">Urgency</p>
              <span className={`badge mt-1 ${referral.urgency === 'Immediate' ? 'badge-urgent' : referral.urgency.includes('Urgent') ? 'badge-warning' : 'badge-neutral'}`}>
                {referral.urgency}
              </span>
            </div>
            <div className="p-3 bg-slate-50 rounded-lg">
              <p className="stat-label">Insurance</p>
              <span className={`badge mt-1 ${referral.insuranceStatus === 'Verified' ? 'badge-success' : referral.insuranceStatus === 'Denied' ? 'badge-urgent' : 'badge-warning'}`}>
                {referral.insuranceStatus}
              </span>
            </div>
          </div>

          {/* Owner & Follow-Up */}
          <div className="grid grid-cols-2 gap-3">
            <div className="flex items-center gap-2 text-sm">
              <User size={13} className="text-slate-400" />
              <span className="text-slate-600">Owner: <strong>{referral.assignedOwner}</strong></span>
            </div>
            <div className="flex items-center gap-2 text-sm">
              <Calendar size={13} className="text-slate-400" />
              <span className="text-slate-600">Follow-up: <strong>{formatDate(referral.nextFollowUpDate)}</strong></span>
            </div>
          </div>

          {/* Decline Reason */}
          {referral.stage === 'Declined' && referral.declineReason && (
            <div className="p-3 bg-red-50 border border-red-200 rounded-lg text-xs text-red-700">
              <p className="font-semibold">Decline Reason</p>
              <p className="mt-1">{referral.declineReason}</p>
              {referral.lostReason && <p className="mt-1 text-red-500">Lost reason: {referral.lostReason}</p>}
            </div>
          )}

          {/* Document Checklist */}
          <div>
            <p className="section-title mb-2 flex items-center gap-2"><FileText size={13} /> Document Checklist</p>
            {referral.documents.filter(d => !d.uploaded).length > 0 && (
              <div className="mb-2 p-2 bg-red-50 border border-red-200 rounded-lg flex items-center gap-2 text-xs text-red-700">
                <AlertTriangle size={11} />
                {referral.documents.filter(d => !d.uploaded).length} missing document{referral.documents.filter(d => !d.uploaded).length > 1 ? 's' : ''}
              </div>
            )}
            <DocChecklist documents={referral.documents} onUpload={(docType) => onUpload(referral.id, docType)} />
          </div>

          {/* SOC Deadline */}
          <div className="p-3 bg-slate-50 rounded-lg">
            <p className="stat-label">SOC Deadline</p>
            <div className="flex items-center gap-2 mt-1">
              <Clock size={13} className="text-slate-500" />
              <span className="text-sm font-medium">{formatDate(referral.dischargeDate)}</span>
              <SLAClock deadline={referral.dischargeDate} />
            </div>
          </div>

          {/* AI Summary */}
          <AISummary referral={referral} />
        </div>
      </div>
    </div>
  );
}

export default function Referrals() {
  const { state, updateReferralStage, updateReferral, addAuditEntry } = useAppState();
  const [viewMode, setViewMode] = useState<'table' | 'kanban'>('table');
  const [filterStage, setFilterStage] = useState('All');
  const [filterUrgency, setFilterUrgency] = useState('All');
  const [selectedReferral, setSelectedReferral] = useState<Referral | null>(null);

  const urgencies = ['All', 'Routine', 'Urgent 24-48 hours', 'Immediate'];

  const filtered = state.referrals.filter(r =>
    (filterStage === 'All' || r.stage === filterStage) &&
    (filterUrgency === 'All' || r.urgency === filterUrgency)
  );

  const handleStageChange = (id: string, newStage: Referral['stage']) => {
    const ref = state.referrals.find(r => r.id === id);
    updateReferralStage(id, newStage);
    addAuditEntry({
      user: state.currentUser.name,
      role: state.currentUser.role,
      action: 'Updated',
      recordType: 'Referral',
      recordId: id,
      details: `Stage changed to ${newStage} for ${ref?.patientInitials}`,
      before: ref?.stage,
      after: newStage,
    });
  };

  const handleDocUpload = (referralId: string, docType: string) => {
    const ref = state.referrals.find(r => r.id === referralId);
    if (!ref) return;
    const updatedDocs = ref.documents.map(d =>
      d.type === docType ? { ...d, uploaded: true, uploadedAt: new Date().toISOString() } : d
    );
    updateReferral(referralId, { documents: updatedDocs, documentsUploaded: updatedDocs.filter(d => d.uploaded).length });
    addAuditEntry({
      user: state.currentUser.name,
      role: state.currentUser.role,
      action: 'Updated',
      recordType: 'Referral',
      recordId: referralId,
      details: `Uploaded ${docType} for ${ref.patientInitials}`,
    });
  };

  const missingDocsCount = state.referrals.reduce((sum, r) => sum + r.documents.filter(d => !d.uploaded).length, 0);

  return (
    <div>
      <div className="flex justify-between items-start mb-6">
        <div>
          <h2 className="page-title flex items-center gap-2">
            <ClipboardList size={22} className="text-advisa-accent" />
            Referral Pipeline
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            {state.referrals.length} referrals · {missingDocsCount} missing docs
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={() => setViewMode('table')} className={`btn-${viewMode === 'table' ? 'primary' : 'secondary'} text-xs py-1.5`}>Table</button>
          <button onClick={() => setViewMode('kanban')} className={`btn-${viewMode === 'kanban' ? 'primary' : 'secondary'} text-xs py-1.5`}>Kanban</button>
        </div>
      </div>

      {/* Filters */}
      <div className="flex gap-3 mb-5 flex-wrap">
        <select className="select" value={filterStage} onChange={e => setFilterStage(e.target.value)}>
          <option value="All">All Stages</option>
          {stages.map(s => <option key={s} value={s}>{s}</option>)}
        </select>
        <select className="select" value={filterUrgency} onChange={e => setFilterUrgency(e.target.value)}>
          {urgencies.map(u => <option key={u} value={u}>{u === 'All' ? 'All Urgencies' : u}</option>)}
        </select>
      </div>

      {viewMode === 'kanban' ? (
        /* Kanban View */
        <div className="flex gap-3 overflow-x-auto pb-4">
          {stages.filter(s => s !== 'Declined').map(stage => {
            const stageReferrals = filtered.filter(r => r.stage === stage);
            return (
              <div key={stage} className="min-w-[220px] flex-shrink-0">
                <div className={`px-3 py-2 rounded-t-lg text-xs font-semibold border ${stageColors[stage]}`}>
                  {stage} ({stageReferrals.length})
                </div>
                <div className="bg-slate-50 border border-t-0 border-advisa-border rounded-b-lg p-2 space-y-2 min-h-[200px]">
                  {stageReferrals.map(r => (
                    <div
                      key={r.id}
                      onClick={() => setSelectedReferral(r)}
                      className="bg-white p-3 rounded-lg border border-advisa-border shadow-sm hover:shadow-card cursor-pointer transition-all"
                    >
                      <div className="flex items-center justify-between mb-1">
                        <span className="font-semibold text-sm text-slate-800">{r.patientInitials}</span>
                        <span className={`badge text-[10px] ${r.urgency === 'Immediate' ? 'badge-urgent' : r.urgency.includes('Urgent') ? 'badge-warning' : 'badge-neutral'}`}>
                          {r.urgency === 'Immediate' ? '🔴' : r.urgency.includes('Urgent') ? '🟡' : '⚪'} {r.urgency.split(' ')[0]}
                        </span>
                      </div>
                      <p className="text-[10px] text-slate-500">{r.source}</p>
                      <p className="text-[10px] text-slate-400">{r.serviceType}</p>
                      <div className="flex items-center justify-between mt-2">
                        <SLAClock deadline={r.slaDeadline} />
                        {r.documents.some(d => !d.uploaded) && (
                          <span className="text-[10px] text-red-500 flex items-center gap-0.5"><AlertTriangle size={9} /> Docs</span>
                        )}
                      </div>
                    </div>
                  ))}
                  {stageReferrals.length === 0 && <p className="text-[10px] text-slate-300 text-center py-4">Empty</p>}
                </div>
              </div>
            );
          })}
        </div>
      ) : (
        /* Table View */
        <div className="card p-0 overflow-hidden">
          <table className="w-full text-sm">
            <thead>
              <tr>
                <th className="table-head">Patient</th>
                <th className="table-head">Service</th>
                <th className="table-head">Urgency</th>
                <th className="table-head">Source</th>
                <th className="table-head">Docs</th>
                <th className="table-head">SLA</th>
                <th className="table-head">Owner</th>
                <th className="table-head">Stage</th>
                <th className="table-head">Actions</th>
              </tr>
            </thead>
            <tbody>
              {filtered.map(r => {
                const missingDocs = r.documents.filter(d => !d.uploaded).length;
                return (
                  <tr key={r.id} className="hover:bg-slate-50 transition-colors">
                    <td className="table-cell font-semibold text-slate-800">{r.patientInitials}</td>
                    <td className="table-cell"><span className="badge badge-info">{r.serviceType}</span></td>
                    <td className="table-cell">
                      <span className={`badge ${r.urgency === 'Immediate' ? 'badge-urgent' : r.urgency.includes('Urgent') ? 'badge-warning' : 'badge-neutral'}`}>
                        {r.urgency}
                      </span>
                    </td>
                    <td className="table-cell text-slate-500">{r.source}</td>
                    <td className="table-cell">
                      {missingDocs > 0 ? (
                        <span className="text-red-600 text-xs font-medium flex items-center gap-1">
                          <AlertTriangle size={11} /> {missingDocs} missing
                        </span>
                      ) : (
                        <span className="text-emerald-600 text-xs flex items-center gap-1">
                          <CheckCircle size={11} /> Complete
                        </span>
                      )}
                    </td>
                    <td className="table-cell"><SLAClock deadline={r.slaDeadline} /></td>
                    <td className="table-cell text-slate-500 text-xs">{r.assignedOwner}</td>
                    <td className="table-cell">
                      <select
                        value={r.stage}
                        onChange={e => handleStageChange(r.id, e.target.value as Referral['stage'])}
                        className="text-xs px-2 py-1 border border-advisa-border rounded-md bg-white"
                      >
                        {stages.map(s => <option key={s} value={s}>{s}</option>)}
                      </select>
                    </td>
                    <td className="table-cell">
                      <button onClick={() => setSelectedReferral(r)} className="text-advisa-accent hover:text-advisa-accent-dark transition-colors">
                        <Eye size={15} />
                      </button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
          {filtered.length === 0 && <div className="text-center py-12 text-slate-400 text-sm">No referrals match your filters</div>}
        </div>
      )}

      {/* Detail Drawer */}
      {selectedReferral && (
        <DetailDrawer
          referral={selectedReferral}
          onClose={() => setSelectedReferral(null)}
          onUpload={handleDocUpload}
        />
      )}
    </div>
  );
}
